os: linux
dist: xenial

language: python

jobs:
  include:
    - python: 3.6
      env: TOX_ENV='flake8'
    # Django 2.2
    - python: 3.6
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.7
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.8
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.9
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.9
      env: DJANGO='dj22' CMS='cms38'

install:
  - pip install coverage tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then export PY_VER=py39; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
